// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDXIoKVcdV39PabtLqqxrtfMkHBcOVcCQ',
    appId: '1:1085218971914:web:207f8af95bf67577001af3',
    messagingSenderId: '1085218971914',
    projectId: 'tripmeet-e54fb',
    authDomain: 'tripmeet-e54fb.firebaseapp.com',
    storageBucket: 'tripmeet-e54fb.firebasestorage.app',
    measurementId: 'G-10ZM4SF8QR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnzwVHIKGGj9vi9mxBy-duQ6gx6DW2-_4',
    appId: '1:1085218971914:android:470567922bd29a68001af3',
    messagingSenderId: '1085218971914',
    projectId: 'tripmeet-e54fb',
    storageBucket: 'tripmeet-e54fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClX7dB3kIbJdKmQ1_47ftmnEOhB_7cHqs',
    appId: '1:1085218971914:ios:d1841cf95e166ada001af3',
    messagingSenderId: '1085218971914',
    projectId: 'tripmeet-e54fb',
    storageBucket: 'tripmeet-e54fb.firebasestorage.app',
    iosBundleId: 'com.example.tripmeet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClX7dB3kIbJdKmQ1_47ftmnEOhB_7cHqs',
    appId: '1:1085218971914:ios:d1841cf95e166ada001af3',
    messagingSenderId: '1085218971914',
    projectId: 'tripmeet-e54fb',
    storageBucket: 'tripmeet-e54fb.firebasestorage.app',
    iosBundleId: 'com.example.tripmeet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDXIoKVcdV39PabtLqqxrtfMkHBcOVcCQ',
    appId: '1:1085218971914:web:4a8d1f5287ee6aa6001af3',
    messagingSenderId: '1085218971914',
    projectId: 'tripmeet-e54fb',
    authDomain: 'tripmeet-e54fb.firebaseapp.com',
    storageBucket: 'tripmeet-e54fb.firebasestorage.app',
    measurementId: 'G-NRN5KK2EKW',
  );
}
